name: illust_guessing_app
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=2.16.1 <3.0.0'

# example: "slidy run test" like npm scripts
scripts:
  test: flutter test -r expanded --no-sound-null-safety
  build: flutter pub run build_runner build

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  json_annotation: ^4.4.0
  json_serializable: ^6.1.4
  freezed_annotation: ^1.1.0
  flutter_riverpod: ^1.0.3
  flutter_hooks: ^0.18.2+1
  hooks_riverpod: ^1.0.3
  universal_platform: ^1.0.0+1
  shared_preferences: 2.0.13
  sqflite: ^2.0.2
  path_provider: ^2.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  build_runner: ^2.1.7
  freezed: ^1.1.1
  mockito: ^5.1.0
  sqflite_common_ffi: ^2.1.0+2

flutter:
  uses-material-design: true
  assets:
    - assets/data/
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
